FROM php:7.2-apache

RUN apt-get update \
  && apt-get install -y wget \
  && rm -rf /var/lib/apt/lists/*

RUN docker-php-ext-install mysqli
RUN docker-php-ext-enable mysqli

WORKDIR /var/www/html

CMD ["php", "-S", "0.0.0.0:8000"]
